apiVersion: v1
kind: Pod
metadata:
  name: s6430-explicitlynoncompliant
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      securityContext:  
        allowPrivilegeEscalation: true # noncompliant