service: aws-python
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  entrypoint:
    handler: ../otherServerless/handler.entrypoint
    events:
      - http:
          path: /test1
          method: get
